Repository rte-antares-rpackage/antaresEditObject, pull requests merged in 2024-04, with the labels that each got.

#149 Ant1316
  NEWS.md
  R/scenarioBuilder.R
  tests/testthat/test-scenarioBuilder.R
Labels: bug

#154 Add control before actions in removeLink(), removeCluster(), removeArea()
  NEWS.md
  R/removeArea.R
  R/removeCluster.R
  R/removeLink.R
  R/utils.R
  man/detect_pattern_in_binding_constraint.Rd
  tests/testthat/test-createArea.R
  tests/testthat/test-createCluster.R
  tests/testthat/test-createDSR.R
  tests/testthat/test-createLink.R
  tests/testthat/test-createPSP.R
Labels: feature

#155 Fix bug removing prepro directory in .removeCluster with thermal mode
  NEWS.md
  R/removeCluster.R
  tests/testthat/test-RES.R
  tests/testthat/test-ST.R
  tests/testthat/test-createCluster.R
  tests/testthat/test-createClusterST.R
  tests/testthat/test-editClusterST.R
  tests/testthat/test-scenarioBuilder.R
Labels: bug

#157 fix rev dep to antaresRead in test
  NEWS.md
  cran-comments.md
  tests/testthat/test-createCluster.R
Labels: release

#158 Release/cran063
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/API-utils.R
  R/createArea.R
  R/createClusterST.R
  R/editClusterST.R
  R/removeArea.R
  R/removeCluster.R
  R/removeLink.R
  R/scenarioBuilder.R
  R/utils.R
  man/create_scb_referential_series_type.Rd
  man/detect_pattern_in_binding_constraint.Rd
  man/scenario-builder.Rd
  tests/testthat/test-RES.R
  tests/testthat/test-ST.R
  tests/testthat/test-createArea.R
  tests/testthat/test-createCluster.R
  tests/testthat/test-createClusterST.R
  tests/testthat/test-createDSR.R
  tests/testthat/test-createLink.R
  tests/testthat/test-createPSP.R
  tests/testthat/test-editClusterST.R
  tests/testthat/test-scenarioBuilder.R
Labels: release
