Repository rte-antares-rpackage/antaresEditObject, pull requests merged in 2024-03, with the labels that each got.

#139 createBindingConstraint() update api part with endpoint
  R/createBindingConstraint.R
Labels: release

#140 ImportZipStudyWeb to upload a local study in Antares Web
  NAMESPACE
  NEWS.md
  R/importStudyAPI.R
  man/importZipStudyWeb.Rd
Labels: feature

#141 Feature/edit bc870
  R/createBindingConstraint.R
  R/editBindingConstraint.R
  man/editBindingConstraint.Rd
Labels: release

#144 Update opts in api mode for createLink
  NEWS.md
  R/createLink.R
Labels: bug

#148 removeBindingConstraint() updated from code review comment + tests
  R/removeBindingConstraint.R
  tests/testthat/test-removeBindingConstraint.R
Labels: release

#147 correct test in createCluster after breaking change in antaresRead
  tests/testthat/test-createCluster.R
Labels: bug
