Repository rte-antares-rpackage/antaresEditObject, pull requests merged in 2024-02, with the labels that each got.

#131 Fix bug for createDSR() in API mode
  NEWS.md
  R/createDSR.R
  tests/testthat/test-createDSR.R
Labels: bug

#130 Fix bug Setplaylist
  NEWS.md
  R/playlist.R
  tests/testthat/test-playlist.R
Labels: bug

#117 Ant946/getjobs
  DESCRIPTION
  NEWS.md
  R/API.R
  R/utils.R
Labels: bug

#133 Ant1070/bugfix
  NEWS.md
  R/createBindingConstraint.R
  man/create-binding-constraint.Rd
  man/editBindingConstraint.Rd
  tests/testthat/test-createBindingConstraint.R
Labels: bug

#135 Ant856/bug
  NEWS.md
  R/createCluster.R
  R/editCluster.R
  man/createCluster.Rd
  tests/testthat/test-createCluster.R
  tests/testthat/test-editCluster.R
Labels: bug

#137 don't forget to check your local NOTES
  .github/workflows/R-CMD-check.yaml
  R/createCluster.R
Labels: help wanted

#138 Feature/scenariobuilderv8.7.0
  R/scenarioBuilder.R
  man/scenario-builder.Rd
  tests/testthat/test-scenarioBuilder.R
Labels: release
